name: Ubuntu 24.04 Rootfs Snapshot - Ultimate (Dockerfile)

on:
  push:
    branches: [main, master]
    paths:
      - 'Dockerfile.ultimate'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-rootfs-ultimate:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 🐳 Build Docker Image (Ultimate)
        run: docker build -f Dockerfile.ultimate -t ubuntu24-dev-ultimate .

      - name: 📦 Generate Snapshot
        run: |
          mkdir -p rootfs-output

          docker run --rm -v ${{ github.workspace }}/rootfs-output:/build ubuntu24-dev-ultimate bash -c '
            set -eux
            mkdir -p /build/ubuntu24-rootfs

            for dir in bin boot etc home lib lib64 opt root sbin srv usr var; do
              cp -a "/$dir" /build/ubuntu24-rootfs || true
            done

            echo "Ubuntu 24.04 Ultimate Dev Snapshot" > /build/ubuntu24-rootfs/README.txt
            cd /build
            tar --ignore-failed-read -czf ubuntu24-ultimate.tar.gz ubuntu24-rootfs
            sha256sum ubuntu24-ultimate.tar.gz > sha256.txt
          '

      - name: ☁️ Upload ke GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v24.04-full-ultimate
          name: Ubuntu 24.04 Rootfs Snapshot (Ultimate)
          files: |
            rootfs-output/ubuntu24-ultimate.tar.gz
            rootfs-output/sha256.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Done
        run: echo "🔥 Snapshot Ultimate Ubuntu 24.04 selesai dibuild & diupload!"
