name: Ultimate Dev Environment - Ubuntu 24.04 FULL

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ultimate-dev-setup:
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: ✅ Checkout Repo
        uses: actions/checkout@v4

      - name: 📅 Set Tanggal dan Nama File
        run: |
          DATE=$(date +%Y-%m-%d)
          echo "TAR_NAME=ubuntu24-dev-env-heavy-$DATE.tar.gz" >> $GITHUB_ENV
          echo "RELEASE_NAME=Ubuntu 24.04 Dev Snapshot - $DATE" >> $GITHUB_ENV
          echo "TAG_NAME=v24.04-heavy-$DATE" >> $GITHUB_ENV

      - name: 🔧 Generate Dummy Config Files (LENGKAP)
        run: |
          mkdir -p ~/.config/nvim
          for i in $(seq 1 500); do echo "\" line $i" >> ~/.config/nvim/init.vim; done

          mkdir -p ~/.config/tmux
          for i in $(seq 1 300); do echo "# tmux config line $i" >> ~/.config/tmux/tmux.conf; done

          echo "# Auto .zshrc" > ~/.zshrc
          for i in $(seq 1 200); do echo "alias cmd$i='echo Hello $i'" >> ~/.zshrc; done

      - name: 🔍 Cek Isi Sebelum Kompresi
        run: |
          ls -la ~/.config/nvim
          ls -la ~/.config/tmux
          head -n 5 ~/.zshrc

      - name: 🗜️ Kompres Snapshot
        run: |
          mkdir -p dev-env-snapshot
          cp -r ~/.config/nvim dev-env-snapshot/config-nvim || true
          cp -r ~/.config/tmux dev-env-snapshot/config-tmux || true
          cp ~/.zshrc dev-env-snapshot/zshrc || true
          echo "Ubuntu 24.04 Dev Snapshot (Heavy Dummy)" > dev-env-snapshot/README.txt
          tar -czf "$TAR_NAME" dev-env-snapshot

      - name: ☁️ Upload Artifact ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu24-dev-env-heavy
          path: ${{ env.TAR_NAME }}

      - name: 🚀 Upload ke GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.TAR_NAME }}
          name: ${{ env.RELEASE_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
